const fs = require('fs');
const path = require('path');

const sites = ['tnb', 'koch'];
const langs = ['th', 'en', 'zh', 'jp'];

const newTranslations = {
    th: {
        quotation: {
            title: "ขอใบเสนอราคา",
            firstName: "First Name (ชื่อ)",
            lastName: "Last Name (นามสกุล)",
            nickName: "Nick name (ชื่อเล่น)",
            phone: "Mobile Phone Number (เบอร์มือถือ)",
            email: "Email",
            productType: "Items inside your box (ประเภทสินค้าที่บรรจุ)",
            productTypeSelect: "เลือกประเภทสินค้าที่บรรจุ",
            ptEngine: "ชิ้นส่วนเครื่องยนต์ (Engine Parts)",
            ptBody: "ชิ้นส่วนตัวถัง (Body Parts)",
            ptSuspension: "ชิ้นส่วนช่วงล่างและระบบส่งกำลัง (Suspension & Transmission)",
            ptElectrical: "ชิ้นส่วนระบบไฟฟ้า (Electrical Parts)",
            ptAccessories: "อุปกรณ์ตกแต่งรถยนต์ (Car Accessories)",
            ptOther: "ชิ้นส่วนรถยนต์อื่นๆ (Other Auto Parts)",
            weight: "Total Weight (น้ำหนักสินค้า)",
            weightPlaceholder: "น้ำหนักรวมสินค้า (กก.) ที่บรรจุภายในกล่อง",
            brand: "Brand name (ชื่อแบรนด์)",
            brandPlaceholder: "Mazda, Toyota, Honda, Isuzu, BMW",
            packagingType: "Packaging Type (ประเภทบรรจุภัณฑ์)",
            pkgSelect: "เลือกประเภทบรรจุภัณฑ์",
            pkgPaper: "กล่องกระดาษ (Paper Box)",
            pkgWooden: "บรรจุภัณฑ์ไม้ (Wooden Packaging)",
            pkgPlastic: "บรรจุภัณฑ์พลาสติก (Plastic Packaging)",
            pkgSteel: "บรรจุภัณฑ์เหล็ก (Steel Packaging)",
            boxSize: "Box Size (ขนาดกล่องที่ต้องการ)",
            width: "กว้าง",
            length: "ยาว",
            height: "สูง",
            unitCm: "ซม.",
            unitMm: "มม.",
            unitInch: "นิ้ว",
            quantity: "Order quantity (จำนวนสั่งซื้อ)",
            reference: "Reference (แนบไฟล์ตัวอย่างอ้างอิงที่ชอบ)",
            fileHint: "Max. file size: 128 MB.",
            comments: "Other Comments (อื่นที่ต้องการแจ้งทีมงาน)",
            submitBtn: "ส่งข้อมูลขอใบเสนอราคา"
        },
        login: {
            titleIn: "เข้าสู่ระบบ",
            username: "ชื่อผู้ใช้",
            password: "รหัสผ่าน",
            submitIn: "เข้าสู่ระบบ",
            socialInText: "หรือเข้าสู่ระบบด้วยแพลตฟอร์มโซเชียล",
            titleUp: "ลงทะเบียน",
            email: "อีเมล",
            submitUp: "ลงทะเบียน",
            socialUpText: "หรือลงทะเบียนด้วยแพลตฟอร์มโซเชียล",
            newcomerTitle: "เพิ่งมาใหม่ใช่ไหม?",
            newcomerText: "ค้นพบโลกแห่งความเป็นไปได้! เข้าร่วมกับเราและสำรวจชุมชนที่มีชีวิตชีวาที่ความคิดเติบโตและการเชื่อมต่อเจริญก้าวหน้า",
            signUpBtn: "ลงทะเบียน",
            memberTitle: "หนึ่งในสมาชิกที่ทรงคุณค่าของเรา",
            memberText: "ขอบคุณที่เป็นส่วนหนึ่งของชุมชนของเรา การปรากฏตัวของคุณช่วยเติมเต็มประสบการณ์ที่มีร่วมกันของเรา มาสานต่อการเดินทางนี้ไปด้วยกัน!",
            signInBtn: "เข้าสู่ระบบ"
        },
        technology: {
            title: "เทคโนโลยีของเรา",
            desc: "นวัตกรรมและระบบอัจฉริยะที่ช่วยยกระดับประสิทธิภาพการจัดการซัพพลายเชนของคุณ",
            vmiTitle: "VMI System",
            vmiDesc: "KOCH ใช้ระบบ Packaging Supply Management System (VMI) ในการบริหารจัดการคำสั่งซื้ออย่างมีประสิทธิภาพ",
            vmi1Topic: "Order Management:",
            vmi1Text: "ลูกค้าสามารถอัปโหลดข้อมูลแผนการผลิตชิ้นส่วนเข้าระบบได้โดยตรง",
            vmi2Topic: "BOM Management:",
            vmi2Text: "ระบบจะทำการจับคู่รายการชิ้นส่วนกับบรรจุภัณฑ์ที่ต้องใช้ (Matching BOM) โดยอัตโนมัติ",
            vmi3Topic: "Automated Workflow:",
            vmi3Text: "มีระบบออกใบสั่งซื้อ (PO Issued auto) และการอนุมัติผ่านระบบ เพื่อความรวดเร็วและแม่นยำ",
            vmi4Topic: "Reporting:",
            vmi4Text: "ติดตามสถานะได้ผ่านรายงานสรุปรายวัน รายสัปดาห์ และรายงานการส่งมอบแบบ Just-in-Time",
            wmsTitle: "WMS System",
            wmsDesc: "ในส่วนของคลังสินค้า KOCH มีระบบที่ดูแลครอบคลุมทั้งกระบวนการ",
            wms1Topic: "Inbound & Storage:",
            wms1Text: "จัดการตั้งแต่การรับสินค้า การคัดแยกพื้นที่ (Sorting) และการจัดเก็บ",
            wms2Topic: "Fulfillment:",
            wms2Text: "บริหารจัดการการหยิบสินค้าตามออร์เดอร์ (Picking) และการจัดเตรียมสินค้าก่อนส่งมอบ (Marshalling) เพื่อประสิทธิภาพสูงสุด",
            tmsTitle: "TMS System",
            tmsDesc: "KOCH พัฒนาซอฟต์แวร์ TMS (Transportation Management System) ขึ้นเอง (In-house) เพื่อให้สอดคล้องกับความต้องการของลูกค้า",
            tms1Topic: "Real-time Tracking:",
            tms1Text: "ติดตามสถานะรถขนส่งและตำแหน่งผ่าน GPS บนแผนที่ได้แบบเรียลไทม์",
            tms2Topic: "Geofencing & QR Code:",
            tms2Text: "ใช้ระบบ Geofencing เพื่อแจ้งเตือนเมื่อรถเข้า-ออกพื้นที่ และใช้ QR Code สำหรับการอัปเดตสถานะที่รวดเร็วและแม่นยำ",
            moqTitle: "Low MOQ Support",
            moqDesc: "ซอฟต์แวร์และระบบ VMI ของ KOCH ช่วยแก้ปัญหาให้ลูกค้าที่ไม่ต้องการสต็อกสินค้าจำนวนมาก ดังนี้",
            moq1Topic: "MOQ 1 Pc:",
            moq1Text: "ระบบรองรับการสั่งซื้อขั้นต่ำเพียง 1 ชิ้น ช่วยให้ลูกค้าไม่ต้องสั่งซื้อในปริมาณมากเกินความจำเป็น",
            moq2Topic: "Daily Delivery Basis:",
            moq2Text: "สนับสนุนการส่งมอบสินค้าเป็นรายวัน โดยสามารถรวมสินค้าหลายรายการ (Combine many items) ในการจัดส่งครั้งเดียวได้",
            moq3Topic: "Cost & Stock Reduction:",
            moq3Text: "ช่วยลดต้นทุนการถือครองสต็อก (Stock Holding Cost) ได้ถึง 55-75% และลดภาระงาน (Workload) ในการสั่งซื้อได้ถึง 31%",
            moq4Topic: "Inventory Optimization:",
            moq4Text: "ป้องกันปัญหาของขาด (Shortage) และเพิ่มความแม่นยำในการส่งมอบได้สูงถึง 99%"
        },
        branches: {
            title: "สาขาโรงงานของเรา",
            desc: "ยกระดับมาตรฐานการผลิตและระบบบริหารคลังสินค้าในระดับสากลเพื่อตอบสนองความต้องการของลูกค้า",
            banbuengTitle: "สาขาบ้านบึง (Ban Bueng)",
            banbuengDesc: "ฐานการผลิตหลักสำหรับบรรจุภัณฑ์กระดาษลูกฟูก (Carton Box) ด้วยพนักงานที่เชี่ยวชาญกว่า 120 ท่าน พร้อมรองรับปริมาณการผลิตขนาดใหญ่",
            banbueng1Topic: "พื้นที่บริการ:",
            banbueng1Text: "1,600 ตารางเมตร",
            banbueng2Topic: "จุดเด่น:",
            banbueng2Text: "เน้นการให้บริการด้านบรรจุภัณฑ์ (Packaging Services) ครบวงจร",
            banbueng3Topic: "กระบวนการ:",
            banbueng3Text: "ควบคุมคุณภาพการผลิตตามมาตรฐานอุตสาหกรรมในทุกขั้นตอน",
            bowinTitle: "สาขาบ่อวิน (Bowin)",
            bowinDesc: "สาขาใหม่ที่ถูกออกแบบมาเพื่อรองรับการขยายตัวในนิคมอุตสาหกรรมบ่อวิน เน้นบริการคลังสินค้าและการจัดการระบบ VMI ให้ใกล้ชิดกับโรงงานลูกค้ามากขึ้น",
            bowin1Topic: "พื้นที่บริการ:",
            bowin1Text: "5,000 ตารางเมตร",
            bowin2Topic: "จุดเด่น:",
            bowin2Text: "เน้นการดำเนินงานด้านระบบคลังสินค้า (Warehouse Operations) อย่างเต็มรูปแบบ",
            bowin3Topic: "ระบบที่ใช้:",
            bowin3Text: "นำระบบบริหารคลังสินค้า (WMS) และ VMI มาประยุกต์ใช้เพื่อความรวดเร็วและแม่นยำ"
        },
        partners: {
            title: "พันธมิตร",
            desc: "ได้รับความไว้วางใจจากพันธมิตรและลูกค้าในอุตสาหกรรมยานยนต์และอุตสาหกรรมที่เกี่ยวข้องอย่างต่อเนื่อง ทั้งผู้ผลิตรถยนต์ (OEM) และซัพพลายเออร์ระดับ Tier 1 ทั่วประเทศ <br><br> เราทำหน้าที่มากกว่าผู้ให้บริการบรรจุภัณฑ์ โดยเป็นพันธมิตรที่ร่วมพัฒนาโซลูชันด้าน Packaging, VMI, Warehouse และ Logistics เพื่อสนับสนุนการดำเนินงานของลูกค้าให้มีประสิทธิภาพสูงสุด <br><br> ความร่วมมือครอบคลุมตั้งแต่การออกแบบบรรจุภัณฑ์ที่เหมาะสมกับชิ้นงาน ไปจนถึงการบริหารจัดการคลังสินค้าและการขนส่งแบบครบวงจรทุกกระบวนการถูกออกแบบให้สอดคล้องกับการผลิตที่ต้องการความแม่นยำ ความรวดเร็ว และการส่งมอบตรงเวลา <br><br> เราพร้อมเติบโตไปพร้อมพันธมิตร และร่วมสร้างความสำเร็จอย่างยั่งยืนในระยะยาว",
            allPartnersTitle: "พันธมิตรทั้งหมดของเรา"
        },
        product: {
            title: "ประเภทสินค้า",
            desc: "ครอบคลุมวัสดุหลากหลายประเภท เช่น กระดาษ ไม้ พลาสติก และเหล็ก",
            catAll: "ทั้งหมด",
            catPaper: "กล่องกระดาษ",
            catWooden: "บรรจุภัณฑ์ไม้",
            catPlastic: "บรรจุภัณฑ์พลาสติก",
            catSteel: "บรรจุภัณฑ์เหล็ก",
            loadMore: "L O A D &nbsp;&nbsp; M O R E"
        }
    },
    en: {
        quotation: {
            title: "Request Quotation",
            firstName: "First Name",
            lastName: "Last Name",
            nickName: "Nickname",
            phone: "Mobile Phone Number",
            email: "Email",
            productType: "Items inside your box",
            productTypeSelect: "Select product type",
            ptEngine: "Engine Parts",
            ptBody: "Body Parts",
            ptSuspension: "Suspension & Transmission",
            ptElectrical: "Electrical Parts",
            ptAccessories: "Car Accessories",
            ptOther: "Other Auto Parts",
            weight: "Total Weight (kg)",
            weightPlaceholder: "Total weight of items inside the box",
            brand: "Brand Name",
            brandPlaceholder: "Mazda, Toyota, Honda, Isuzu, BMW",
            packagingType: "Packaging Type",
            pkgSelect: "Select packaging type",
            pkgPaper: "Paper Box",
            pkgWooden: "Wooden Packaging",
            pkgPlastic: "Plastic Packaging",
            pkgSteel: "Steel Packaging",
            boxSize: "Box Size",
            width: "Width",
            length: "Length",
            height: "Height",
            unitCm: "cm",
            unitMm: "mm",
            unitInch: "inch",
            quantity: "Order Quantity",
            reference: "Reference (Upload example file)",
            fileHint: "Max. file size: 128 MB.",
            comments: "Other Comments",
            submitBtn: "Submit Quotation Request"
        },
        login: {
            titleIn: "Sign In",
            username: "Username",
            password: "Password",
            submitIn: "Login",
            socialInText: "Or sign in with social platforms",
            titleUp: "Sign Up",
            email: "Email",
            submitUp: "Sign Up",
            socialUpText: "Or sign up with social platforms",
            newcomerTitle: "New here?",
            newcomerText: "Discover a world of possibilities! Join us and explore a vibrant community where ideas grow and connections thrive.",
            signUpBtn: "Sign Up",
            memberTitle: "One of our valued members?",
            memberText: "Thank you for being part of our community. Your presence enriches our shared experience. Let's continue this journey together!",
            signInBtn: "Sign In"
        },
        technology: {
            title: "Our Technology",
            desc: "Innovative and intelligent systems to elevate your supply chain management efficiency.",
            vmiTitle: "VMI System",
            vmiDesc: "KOCH utilizes a Packaging Supply Management System (VMI) to effectively manage orders.",
            vmi1Topic: "Order Management:",
            vmi1Text: "Customers can directly upload production part plans into the system.",
            vmi2Topic: "BOM Management:",
            vmi2Text: "The system automatically matches parts with required packaging (Matching BOM).",
            vmi3Topic: "Automated Workflow:",
            vmi3Text: "Automated Purchase Order issuance (PO Issued auto) and system approvals ensure speed and accuracy.",
            vmi4Topic: "Reporting:",
            vmi4Text: "Track status via daily/weekly summary reports and Just-in-Time delivery reports.",
            wmsTitle: "WMS System",
            wmsDesc: "For warehousing, KOCH provides a comprehensive management system covering all processes.",
            wms1Topic: "Inbound & Storage:",
            wms1Text: "Manages goods receipt, space sorting, and storage.",
            wms2Topic: "Fulfillment:",
            wms2Text: "Manages order picking and marshalling for maximum efficiency before delivery.",
            tmsTitle: "TMS System",
            tmsDesc: "KOCH developed an in-house TMS (Transportation Management System) to meet customer needs.",
            tms1Topic: "Real-time Tracking:",
            tms1Text: "Track transport vehicles and locations via GPS on a map in real-time.",
            tms2Topic: "Geofencing & QR Code:",
            tms2Text: "Uses Geofencing alerts when vehicles enter/exit areas and QR Codes for fast and accurate status updates.",
            moqTitle: "Low MOQ Support",
            moqDesc: "KOCH's software and VMI system help customers avoid large inventory stocks:",
            moq1Topic: "MOQ 1 Pc:",
            moq1Text: "The system supports a minimum order quantity of 1 piece, eliminating the need to overstock.",
            moq2Topic: "Daily Delivery Basis:",
            moq2Text: "Supports daily deliveries, allowing multiple items to be combined in a single shipment.",
            moq3Topic: "Cost & Stock Reduction:",
            moq3Text: "Reduces stock holding costs by 55-75% and ordering workload by up to 31%.",
            moq4Topic: "Inventory Optimization:",
            moq4Text: "Prevents shortage problems and increases delivery accuracy up to 99%."
        },
        branches: {
            title: "Our Factory Branches",
            desc: "Elevating production standards and world-class warehouse management systems to meet customer demands.",
            banbuengTitle: "Ban Bueng Branch",
            banbuengDesc: "The main production base for corrugated packaging (Carton Box) with over 120 expert staff, ready to support large-scale production volumes.",
            banbueng1Topic: "Service Area:",
            banbueng1Text: "1,600 square meters",
            banbueng2Topic: "Highlight:",
            banbueng2Text: "Focuses on comprehensive Packaging Services.",
            banbueng3Topic: "Process:",
            banbueng3Text: "Quality control follows industrial standards at every step.",
            bowinTitle: "Bowin Branch",
            bowinDesc: "A new branch designed to support expansion in the Bowin Industrial Estate, focusing on warehouse services and VMI management to be closer to customer factories.",
            bowin1Topic: "Service Area:",
            bowin1Text: "5,000 square meters",
            bowin2Topic: "Highlight:",
            bowin2Text: "Focuses on full-scale Warehouse Operations.",
            bowin3Topic: "Systems Used:",
            bowin3Text: "Implements Warehouse Management System (WMS) and VMI for speed and accuracy."
        },
        partners: {
            title: "Partners",
            desc: "Continuously trusted by partners and customers in the automotive and related industries, including OEMs and Tier 1 suppliers nationwide. <br><br> We act as more than just a packaging provider; we are partners collaborating to develop Packaging, VMI, Warehouse, and Logistics solutions to maximize our customers' operational efficiency. <br><br> Our collaboration ranges from designing appropriate packaging for parts to comprehensive management of warehousing and transportation. Every process is designed to align with production needs requiring precision, speed, and on-time delivery. <br><br> We are ready to grow alongside our partners and build sustainable success together in the long term.",
            allPartnersTitle: "All Our Partners"
        },
        product: {
            title: "Product Categories",
            desc: "Covering a variety of materials including Paper, Wood, Plastic, and Steel",
            catAll: "All",
            catPaper: "Paper Box",
            catWooden: "Wooden Packaging",
            catPlastic: "Plastic Packaging",
            catSteel: "Steel Packaging",
            loadMore: "L O A D &nbsp;&nbsp; M O R E"
        }
    },
    zh: {
        quotation: {
            title: "请求报价",
            firstName: "名字",
            lastName: "姓氏",
            nickName: "昵称",
            phone: "手机号码",
            email: "电子邮件",
            productType: "包装箱内物品类型",
            productTypeSelect: "选择包装物品类型",
            ptEngine: "发动机零件",
            ptBody: "车身零件",
            ptSuspension: "悬挂及传动零件",
            ptElectrical: "电气系统零件",
            ptAccessories: "汽车配件",
            ptOther: "其他汽车零件",
            weight: "总重量",
            weightPlaceholder: "包装箱内物品总重量 (公斤)",
            brand: "品牌名称",
            brandPlaceholder: "例如马自达，丰田，本田，五十铃，宝马",
            packagingType: "包装类型",
            pkgSelect: "选择包装类型",
            pkgPaper: "纸箱",
            pkgWooden: "木质包装",
            pkgPlastic: "塑料包装",
            pkgSteel: "钢制包装",
            boxSize: "所需纸箱尺寸",
            width: "宽",
            length: "长",
            height: "高",
            unitCm: "厘米",
            unitMm: "毫米",
            unitInch: "英寸",
            quantity: "订购数量",
            reference: "参考（附上样板文件）",
            fileHint: "最大文件大小：128 MB。",
            comments: "其他意见（需通知团队的其他事宜）",
            submitBtn: "提交报价请求"
        },
        login: {
            titleIn: "登录",
            username: "用户名",
            password: "密码",
            submitIn: "登录",
            socialInText: "或使用社交平台登录",
            titleUp: "注册",
            email: "电子邮件",
            submitUp: "注册",
            socialUpText: "或使用社交平台注册",
            newcomerTitle: "新来的吗？",
            newcomerText: "发现一个充满可能性的世界！加入我们，探索一个充满活力的社区，在这里，想法在成长，联系在繁荣。",
            signUpBtn: "注册",
            memberTitle: "我们尊贵的会员之一？",
            memberText: "感谢您成为我们社区的一员。您的存在丰富了我们共同的经验。让我们一起继续这段旅程！",
            signInBtn: "登录"
        },
        technology: {
            title: "我们的技术",
            desc: "创新及智能系统，提升您的供应链管理效率。",
            vmiTitle: "VMI 系统",
            vmiDesc: "KOCH 使用包装供应管理系统 (VMI) 来有效管理订单。",
            vmi1Topic: "订单管理：",
            vmi1Text: "客户可直接将零件生产计划数据上传至系统。",
            vmi2Topic: "BOM 管理：",
            vmi2Text: "系统将自动匹配所需零件物料清单与包装的对应关系。",
            vmi3Topic: "自动工作流：",
            vmi3Text: "系统自动发行采购订单（PO），并通过系统审批以确保快速和准确。",
            vmi4Topic: "报告：",
            vmi4Text: "通过每日、每周总结报告及即时准时交付（JIT）报告进行追踪状态。",
            wmsTitle: "WMS 系统",
            wmsDesc: "在仓储管路方面，KOCH 拥有涵盖整个过程的全面系统。",
            wms1Topic: "入库及存储：",
            wms1Text: "管理从收货、区域分类（Sorting）到存储等过程。",
            wms2Topic: "履行订单：",
            wms2Text: "管理按订单拣选货物及发货前的准备（Marshalling），以实现最高效率。",
            tmsTitle: "TMS 系统",
            tmsDesc: "KOCH 自主开发运输管理软件 (TMS)，以符合客户需求。",
            tms1Topic: "实时追踪：",
            tms1Text: "能在地图上通过 GPS 实时跟查运输车辆的位置及状态。",
            tms2Topic: "地理围栏与二维码：",
            tms2Text: "使用地理围栏系统来提醒车辆进出区域，使用二维码可快速准确地更新进度状态。",
            moqTitle: "支持低 MOQ",
            moqDesc: "KOCH的软件与VMI系统，可协助需要解决不想拥有大量库存烦恼的客户：",
            moq1Topic: "1 件起订量：",
            moq1Text: "系统支持只需 1 件订购的底限，让客户避免不必要的超量订购烦恼。",
            moq2Topic: "每日交付基准：",
            moq2Text: "支持以每日的交付形式送货，通过单次发货进行多种商品发运。",
            moq3Topic: "减少成本与库存：",
            moq3Text: "有效削减持有库存成本 55-75%，工作量最高也减少至 31%。",
            moq4Topic: "库存优化：",
            moq4Text: "有效防止缺货问题发上，并增加多达 99% 精确送货度。"
        },
        branches: {
            title: "我们的工厂分支机构",
            desc: "提升国际级生产标准及仓储系统，以满足客户的需求",
            banbuengTitle: "Ban Bueng 分支机构",
            banbuengDesc: "纸箱（Carton Box）的主要生产基地，拥有超过 120 名专业人员，能够支持大规模生产量。",
            banbueng1Topic: "服务面积：",
            banbueng1Text: "1,600 平方米",
            banbueng2Topic: "亮点：",
            banbueng2Text: "专注于提供全方位的包装服务。",
            banbueng3Topic: "过程：",
            banbueng3Text: "在每个步骤中遵循工业标准进行生产质量控制。",
            bowinTitle: "Bowin 分支机构",
            bowinDesc: "新成立的分支机构，旨在支持Bowin工业园区的扩张，重点提供仓库服务与VMI管理，以便更加贴近客户的工厂。",
            bowin1Topic: "服务面积：",
            bowin1Text: "5,000 平方米",
            bowin2Topic: "亮点：",
            bowin2Text: "专注于全面实施的仓库运营管理。",
            bowin3Topic: "使用系统：",
            bowin3Text: "结合仓库管理系统（WMS）和 VMI，达到迅捷又精准度。"
        },
        partners: {
            title: "合作伙伴",
            desc: "我们的服务不断获得了汽车及其相关行业领域客户伙伴的信任。其中包括整车制造商（OEM）和全国一流（Tier 1）的供应商。<br><br> 我们不仅仅只是扮演一个包装供应的角色。作为协作伙伴，从包装设计，VMI ，仓储，以及物流，协助客户企业运营的最大效率方案。<br><br> 从提供切合零件设计特性的包装方案到全面整合的完整过程，满足精确并且快速能准时送达目标的运营管理。 <br><br> 我们立志与伙伴共同成长，共享长久且持续成功的经验。",
            allPartnersTitle: "我们所有的合作伙伴"
        },
        product: {
            title: "产品类别",
            desc: "涵盖纸、木、塑料、钢等多种材料",
            catAll: "全部",
            catPaper: "纸箱",
            catWooden: "木质包装",
            catPlastic: "塑料包装",
            catSteel: "钢制包装",
            loadMore: "加 载 更 多"
        }
    },
    jp: {
        quotation: {
            title: "見積もりのご依頼",
            firstName: "名（名前）",
            lastName: "姓（名字）",
            nickName: "ニックネーム",
            phone: "携帯電話番号",
            email: "メールアドレス",
            productType: "梱包する商品の種類",
            productTypeSelect: "商品の種類を選択してください",
            ptEngine: "エンジン部品",
            ptBody: "ボディ部品",
            ptSuspension: "サスペンションおよびトランスミッション部品",
            ptElectrical: "電気システム部品",
            ptAccessories: "カーアクセサリー",
            ptOther: "その他の自動車部品",
            weight: "総重量",
            weightPlaceholder: "箱に梱包する全商品の総重量 (kg)",
            brand: "ブランド名",
            brandPlaceholder: "例：マツダ、トヨタ、ホンダ、いすゞ、BMWなど",
            packagingType: "梱包タイプ",
            pkgSelect: "梱包タイプを選択してください",
            pkgPaper: "紙箱",
            pkgWooden: "木製梱包",
            pkgPlastic: "プラスチック梱包",
            pkgSteel: "スチール梱包",
            boxSize: "ご希望の箱のサイズ",
            width: "幅",
            length: "長さ",
            height: "高さ",
            unitCm: "cm",
            unitMm: "mm",
            unitInch: "インチ",
            quantity: "注文数量",
            reference: "参考資料（参考ファイルの添付）",
            fileHint: "最大ファイルサイズ：128 MB。",
            comments: "その他のコメント（チームにお知らせしたいこと）",
            submitBtn: "見積もりリクエストを送信"
        },
        login: {
            titleIn: "ログイン",
            username: "ユーザー名",
            password: "パスワード",
            submitIn: "ログイン",
            socialInText: "またはソーシャルプラットフォームでログイン",
            titleUp: "サインアップ",
            email: "メールアドレス",
            submitUp: "サインアップ",
            socialUpText: "またはソーシャルプラットフォームで登録",
            newcomerTitle: "初めてですか？",
            newcomerText: "可能性の世界を発見しましょう！参加して、アイデアが育ち、つながりが繁栄する活気あるコミュニティを探索してください。",
            signUpBtn: "サインアップ",
            memberTitle: "すでに会員ですか？",
            memberText: "私たちのコミュニティの一部であり続けていただきありがとうございます。あなたの存在が私たちの共有する経験を豊かにします。一緒にこの旅を続けましょう！",
            signInBtn: "ログイン"
        },
        technology: {
            title: "私たちのテクノロジー",
            desc: "サプライチェーン管理の効率を向上させる革新的かつインテリジェントなシステム。",
            vmiTitle: "VMI システム",
            vmiDesc: "KOCH は包装供給管理システム（VMI）を活用して、注文を効率的に管理しています。",
            vmi1Topic: "注文管理：",
            vmi1Text: "顧客は部品生産計画データをシステムに直接アップロードできます。",
            vmi2Topic: "BOM 管理：",
            vmi2Text: "システムが自動的に部品アイテムと必要なパッケージを照合します（Matching BOM）。",
            vmi3Topic: "自動ワークフロー：",
            vmi3Text: "迅速かつ正確性を維持するため、システムを通じて自動的に発注書を発行（PO Issued auto）および承認します。",
            vmi4Topic: "レポート：",
            vmi4Text: "日次・週次のレポートサマリー、及びジャストインタイム（JIT）納品レポートを通じてステータスを追跡。",
            wmsTitle: "WMS システム",
            wmsDesc: "倉庫業務に関して、KOCH はプロセス全体をカバーするシステムを備えています。",
            wms1Topic: "入荷および保管：",
            wms1Text: "商品の受け取り、分類（Sorting）、そして保管までを管理。",
            wms2Topic: "フルフィルメント：",
            wms2Text: "効率的な注文商品のピッキング（Picking）および出荷前の準備（Marshalling）の管理。",
            tmsTitle: "TMS システム",
            tmsDesc: "KOCH はお客様のニーズに合わせ、自社開発（In-house）の TMS ソフトウェアを構築しました。",
            tms1Topic: "リアルタイム・トラッキング：",
            tms1Text: "GPS を使用して輸送車両の状態と位置をマップ上でリアルタイムに追跡。",
            tms2Topic: "ジオフェンシングと QR コード：",
            tms2Text: "車両のエリア出入時のジオフェンシングによる警告通知、QR コードを使用した正確で迅速なステータス更新。",
            moqTitle: "低 MOQ のサポート",
            moqDesc: "大量の在庫を抱えたくない顧客の問題を KOCH の VMI ソフトウェアおよびシステムが解決します。",
            moq1Topic: "MOQ 1 個：",
            moq1Text: "最小発注量として 1 個から注文をサポートし、不要な大量注文を回避します。",
            moq2Topic: "毎日の納品基準：",
            moq2Text: "日々の配送をサポートし、一回の納品で複数の商品をまとめることが可能。",
            moq3Topic: "コストと在庫の削減：",
            moq3Text: "在庫保有コストを最大 55-75% 削減、注文に係るワークロードを最高 31% 削減。",
            moq4Topic: "在庫の最適化：",
            moq4Text: "不足の問題を防ぎ、納品の精度を最大 99% まで向上。"
        },
        branches: {
            title: "工場の拠点情報",
            desc: "顧客のニーズに応えるべく、生産基準と国際的な倉庫管理システムを向上",
            banbuengTitle: "バーンブン支店（Ban Bueng）",
            banbuengDesc: "段ボール包装（Carton Box）の主要生産拠点であり、120 名以上の専門スタッフが配置され、大規模な生産量にも対応可能。",
            banbueng1Topic: "サービスエリア：",
            banbueng1Text: "1,600 平方メートル",
            banbueng2Topic: "ハイライト：",
            banbueng2Text: "包括的なパッケージング・サービスの提供に注力。",
            banbueng3Topic: "プロセス：",
            banbueng3Text: "全段階において業界標準に基づく生産品質の管理を実施。",
            bowinTitle: "ボーウィン支店（Bowin）",
            bowinDesc: "ボーウィン工業団地における事業拡大に対応するため設計された新支店。顧客の工場に密着した倉庫サービスとVMI管理の提供に焦点を当てています。",
            bowin1Topic: "サービスエリア：",
            bowin1Text: "5,000 平方メートル",
            bowin2Topic: "ハイライト：",
            bowin2Text: "倉庫運営管理を全面的に展開。",
            bowin3Topic: "使用システム：",
            bowin3Text: "迅速性と正確性を確保するため、倉庫管理システム（WMS）および VMI を活用。"
        },
        partners: {
            title: "パートナーシップ",
            desc: "自動車産業および関連産業のパートナーやお客様、OEMおよび全国のTier 1サプライヤーから継続的に信頼をいただいております。<br><br> 私たちは単なる包装プロバイダーとしてではなく、パッケージング、VMI、倉庫、物流のソリューションを共同開発するパートナーとして、お客様の業務を最高効率でサポートします。<br><br> 製品の要求する仕様に合わせた適切な包装から倉庫・輸送まで包括的に管理・設計し、精度とスピード、時間通りにお届けできる体制を整えています。<br><br> 私たちはパートナーと共に成長し、持続的な成功を長期にわたり築く準備ができております。",
            allPartnersTitle: "すべてのパートナー"
        },
        product: {
            title: "製品カテゴリ",
            desc: "紙、木材、プラスチック、スチールなど様々な素材を網羅",
            catAll: "すべて",
            catPaper: "紙箱",
            catWooden: "木製梱包",
            catPlastic: "プラスチック梱包",
            catSteel: "スチール梱包",
            loadMore: "もっと見る"
        }
    }
};

sites.forEach(site => {
    langs.forEach(lang => {
        const filePath = path.join(__dirname, site, 'lang', `${lang}.json`);
        if (fs.existsSync(filePath)) {
            const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
            
            // Merge new translations
            data.quotation = newTranslations[lang].quotation;
            data.login = newTranslations[lang].login;
            data.technology = newTranslations[lang].technology;
            data.branches = newTranslations[lang].branches;
            data.partners = newTranslations[lang].partners;
            data.product = newTranslations[lang].product;
            
            fs.writeFileSync(filePath, JSON.stringify(data, null, 4));
            console.log(`Updated ${site}/lang/${lang}.json`);
        }
    });
});
