const fs = require('fs');
const path = require('path');

const translations = {
  th: {
    service: {
      dev_title: "Packaging Development",
      dev_subtitle: "นวัตกรรมการออกแบบบรรจุภัณฑ์ครบวงจร",
      dev_desc: "ให้บริการพัฒนาและออกแบบบรรจุภัณฑ์สำหรับอุตสาหกรรมยานยนต์แบบครบวงจร ครอบคลุมวัสดุหลากหลายประเภท เช่น กระดาษ เหล็ก ไม้ และพลาสติก โดยมุ่งเน้นการออกแบบที่แข็งแรง ปลอดภัย และเหมาะสมกับการขนส่งและการจัดเก็บ กระบวนการพัฒนาบรรจุภัณฑ์ของบริษัทดำเนินงานอย่างเป็นระบบ ตั้งแต่การออกแบบแนวคิด การสร้างต้นแบบ การทดสอบใช้งานจริง ไปจนถึงการอนุมัติใช้งาน ภายใต้กรอบระยะเวลาการทำต้นแบบภายใน 7 วัน เพื่อความรวดเร็วและแม่นยำในการตอบสนองความต้องการของลูกค้า",
      dev_sec1_title: "งานวิศวกรรมภายใน",
      dev_sec1_desc: "เปี่ยมด้วยประสบการณ์และความเชี่ยวชาญ โดยทีมงานของเราไม่ได้ทำหน้าที่เพียงแค่การผลิตบรรจุภัณฑ์ทั่วไป แต่เป็นการออกแบบโซลูชันเชิงวิศวกรรมที่ปรับแต่งให้เหมาะสมกับความต้องการเฉพาะของแต่ละโครงการอย่างใกล้ชิด",
      dev_sec2_title: "การพัฒนาระบบดิจิทัลและนวัตกรรม",
      dev_sec2_desc: "การพัฒนาระบบซอฟต์แวร์บริหารจัดการการขนส่ง (TMS System) ขึ้นด้วยทีมงานภายในของเราเอง เพื่อให้มั่นใจว่าระบบจะสามารถสอดคล้องกับข้อกำหนดและความต้องการที่หลากหลายของลูกค้าแต่ละรายได้อย่างไร้รอยต่อ",
      dev_sec3_title: "เครื่องมือและเทคโนโลยีขั้นสูง",
      dev_sec3_desc: "การใช้ซอฟต์แวร์มาตรฐานโลกอย่าง AutoCAD และ SolidWorks 3D เพื่อสร้างสรรค์โครงสร้างบรรจุภัณฑ์ที่มีความแม่นยำและซับซ้อนสูง จากนั้นจึงนำระบบการตัดด้วยดิจิทัล (Digital-Cutting Optimization System) มาใช้ในกระบวนการเตรียมวัสดุเพื่อลดการสูญเสียและเพิ่มความรวดเร็วในการผลิต",
      
      wh_title: "Warehouse & Operation",
      wh_subtitle: "บริหารจัดการคลังสินค้าและงานปฏิบัติการมืออาชีพ",
      wh_desc: "ดูแลคลังสินค้าครบวงจรตั้งแต่การรับเข้า จัดเก็บ สุ่มตรวจ และกระจายสินค้า ด้วยมาตรฐานระดับสากล เพื่อให้กระบวนการผลิตของคุณไม่สะดุด",
      wh_li1: "ระบบจัดเก็บสินค้าอย่างเป็นหมวดหมู่และเข้าถึงง่าย (Smart Storage)",
      wh_li2: "การทำงานที่รวดเร็ว ถูกต้อง และแม่นยำ (Fast Operation)",
      wh_li3: "บุคลากรที่มีความเชี่ยวชาญเฉพาะด้าน (Professional Staff)",
      wh_li4: "บูรณาการข้อมูลร่วมกับระบบซัพพลายเชนของคุณ",
      wh_sec1_title: "ระบบจัดเก็บสินค้าเป็นหมวดหมู่และเข้าถึงง่าย",
      wh_sec1_desc: "ออกแบบพื้นที่จัดเก็บอย่างเป็นระบบ แบ่งหมวดหมู่ชัดเจนตามประเภทสินค้าและความถี่ในการใช้งาน ช่วยให้ค้นหาและเบิกจ่ายได้รวดเร็ว ลดความผิดพลาด และเพิ่มประสิทธิภาพในการบริหารพื้นที่คลังสินค้าอย่างคุ้มค่าสูงสุด",
      wh_sec2_title: "การทำงานที่รวดเร็ว ถูกต้อง และแม่นยำ",
      wh_sec2_desc: "ดำเนินงานภายใต้มาตรฐานขั้นตอนที่ชัดเจน พร้อมระบบสนับสนุนที่ช่วยลดความซ้ำซ้อนและข้อผิดพลาด เพิ่มความรวดเร็วในการปฏิบัติงาน ควบคุมคุณภาพได้อย่างต่อเนื่อง และตอบสนองความต้องการลูกค้าได้อย่างตรงเวลา",
      wh_sec3_title: "บุคลากรที่มีความเชี่ยวชาญเฉพาะด้าน",
      wh_sec3_desc: "ทีมงานผ่านการอบรมและมีประสบการณ์ตรงในสายงานโลจิสติกส์และคลังสินค้า เข้าใจขั้นตอนการทำงานอย่างละเอียด สามารถวิเคราะห์ปัญหาและแก้ไขสถานการณ์ได้อย่างมืออาชีพ เพื่อให้การดำเนินงานเป็นไปอย่างราบรื่นและมีประสิทธิภาพสูงสุด",
      
      trans_title: "Transportation Inhouse Fleet",
      trans_subtitle: "ระบบขนส่งอัจฉริยะแบบครบวงจร",
      trans_desc: "บริการขนส่งที่รวดเร็ว ตรงต่อเวลา และปลอดภัย ด้วยกองรถขนส่งภายในบริษัท (Inhouse Fleet) พร้อมระบบติดตามสถานะแบบเรียลไทม์",
      trans_li1: "ครอบคลุมทุกเส้นทางอุตสาหกรรมในประเทศ",
      trans_li2: "ควบคุมคุณภาพและความปลอดภัยตลอดเส้นทาง",
      trans_li3: "รองรับการขนส่งชิ้นส่วนยานยนต์ที่มีความละเอียดอ่อน",
      trans_li4: "ทำงานสอดคล้องกับระบบบริหารจัดการคลังสินค้า",
      trans_sec1_title: "ครอบคลุมทุกเส้นทางอุตสาหกรรมในประเทศ",
      trans_sec1_desc: "ให้บริการขนส่งครอบคลุมทุกภูมิภาคและนิคมอุตสาหกรรมสำคัญทั่วประเทศ วางแผนเส้นทางอย่างมีประสิทธิภาพเพื่อให้การจัดส่งเป็นไปตามกำหนดเวลา รองรับทั้งงานขนส่งประจำและงานเร่งด่วนได้อย่างยืดหยุ่น",
      trans_sec2_title: "ควบคุมคุณภาพและความปลอดภัยตลอดเส้นทาง",
      trans_sec2_desc: "ดำเนินงานภายใต้มาตรฐานด้านความปลอดภัยและคุณภาพในทุกขั้นตอน ตั้งแต่การรับสินค้า การจัดเก็บ ไปจนถึงการจัดส่งปลายทาง พร้อมระบบติดตามและตรวจสอบสถานะแบบต่อเนื่อง เพื่อลดความเสี่ยงและสร้างความมั่นใจสูงสุด",
      trans_sec3_title: "รองรับการขนส่งชิ้นส่วนยานยนต์ที่มีความละเอียดอ่อน",
      trans_sec3_desc: "มีความพร้อมในการดูแลและขนส่งชิ้นส่วนที่ต้องการความระมัดระวังเป็นพิเศษ ด้วยอุปกรณ์เฉพาะทางและขั้นตอนการจัดการที่ได้มาตรฐาน ป้องกันความเสียหายระหว่างการขนส่ง และรักษาคุณภาพของสินค้าให้ครบถ้วนสมบูรณ์จนถึงปลายทาง",
      
      sup_title: "Supply Management",
      sup_subtitle: "ระบบบริหารจัดการบรรจุภัณฑ์อัจฉริยะ",
      sup_desc: "ยกระดับการจัดการบรรจุภัณฑ์ด้วยระบบ (Packaging Supply Management System) ที่ครอบคลุม ติดตามได้อย่างแม่นยำ และลดต้นทุนแอบแฝงในกระบวนการผลิต",
      sup_li1: "ติดตามสถานะบรรจุภัณฑ์หมุนเวียน (Returnable Packaging Tracking)",
      sup_li2: "บริหารจัดการสินค้าคงคลังบรรจุภัณฑ์ (Inventory Management)",
      sup_li3: "วิเคราะห์ข้อมูลและวางแผนการใช้งาน (Data Analytics & Planning)",
      sup_li4: "ลดความสูญเสียและบรรจุภัณฑ์สูญหายอย่างมีประสิทธิภาพ",
      sup_sec1_title: "ติดตามสถานะบรรจุภัณฑ์",
      sup_sec1_desc: "ติดตามการหมุนเวียนของบรรจุภัณฑ์แบบใช้ซ้ำได้อย่างเป็นระบบ ตั้งแต่การจ่ายออก การใช้งาน จนถึงการส่งคืน ช่วยลดการสูญหาย เพิ่มความโปร่งใส และควบคุมต้นทุนได้อย่างมีประสิทธิภาพ",
      sup_sec2_title: "บริหารจัดการสินค้าคงคลังบรรจุภัณฑ์",
      sup_sec2_desc: "ควบคุมปริมาณบรรจุภัณฑ์คงคลังให้เหมาะสมกับปริมาณงานจริง ตรวจสอบสถานะคงเหลือแบบเรียลไทม์ ลดปัญหาขาดแคลนหรือสต็อกเกินความจำเป็น",
      sup_sec3_title: "วิเคราะห์ข้อมูลและวางแผนการใช้งาน",
      sup_sec3_desc: "นำข้อมูลการใช้งานมาวิเคราะห์แนวโน้มและประสิทธิภาพ เพื่อวางแผนการจัดสรรบรรจุภัณฑ์ให้สอดคล้องกับปริมาณงาน ช่วยเพิ่มความแม่นยำในการตัดสินใจและลดต้นทุนในระยะยาว",
      
      card_inventory: "บริหารจัดการสินค้าคงคลังบรรจุภัณฑ์",
      card_dev: "นวัตกรรมการออกแบบบรรจุภัณฑ์ครบวงจร",
      card_personnel: "บุคลากรที่มีความเชี่ยวชาญเฉพาะด้าน",
      card_sensitive: "รองรับการขนส่งชิ้นส่วนยานยนต์ที่มีความละเอียดอ่อน",
      card_route: "ครอบคลุมทุกเส้นทางอุตสาหกรรมในประเทศ"
    }
  },
  en: {
    service: {
      dev_title: "Packaging Development",
      dev_subtitle: "Comprehensive Packaging Design Innovation",
      dev_desc: "Providing comprehensive packaging development and design services for the automotive industry, covering a wide range of materials such as paper, steel, wood, and plastic, with a focus on strong, safe designs suitable for transportation and storage. The company's packaging development process operates systematically, from conceptual design, prototyping, real-world testing, to final approval, all within a 7-day prototyping timeframe for fast and accurate customer response.",
      dev_sec1_title: "In-house Engineering",
      dev_sec1_desc: "Full of experience and expertise, our team doesn't just produce standard packaging, but closely designs engineered solutions customized to the specific needs of each project.",
      dev_sec2_title: "Digital Systems & Innovation",
      dev_sec2_desc: "Developing a Transportation Management System (TMS) with our own in-house team to ensure the system seamlessly aligns with the diverse requirements and needs of each customer.",
      dev_sec3_title: "Advanced Tools & Technology",
      dev_sec3_desc: "Using world-class software like AutoCAD and SolidWorks 3D to create highly precise and complex packaging structures, followed by a Digital-Cutting Optimization System in material preparation to reduce waste and accelerate production.",
      
      wh_title: "Warehouse & Operation",
      wh_subtitle: "Professional Warehouse and Operations Management",
      wh_desc: "Comprehensive warehouse management from receiving, storing, random checking, and distributing goods, using international standards to ensure your production process is uninterrupted.",
      wh_li1: "Categorized and easily accessible storage system (Smart Storage)",
      wh_li2: "Fast, correct, and accurate operations (Fast Operation)",
      wh_li3: "Specialized expert personnel (Professional Staff)",
      wh_li4: "Data integration with your supply chain system",
      wh_sec1_title: "Categorized and Easily Accessible Storage System",
      wh_sec1_desc: "Systematically designed storage space, clearly categorized by product type and frequency of use, allowing for fast retrieval, reducing errors, and maximizing warehouse space management efficiency.",
      wh_sec2_title: "Fast, Correct, and Accurate Operations",
      wh_sec2_desc: "Operating under clear standard procedures with support systems that reduce redundancy and errors, accelerating operations while continuously controlling quality and meeting customer demands on time.",
      wh_sec3_title: "Specialized Expert Personnel",
      wh_sec3_desc: "Our team consists of trained professionals with direct experience in logistics and warehousing. They understand operational procedures in detail and can analyze problems and resolve situations professionally to ensure smooth and highly efficient operations.",
      
      trans_title: "Transportation Inhouse Fleet",
      trans_subtitle: "Comprehensive Smart Transportation System",
      trans_desc: "Fast, punctual, and safe transportation services with our company's In-house Fleet, featuring a real-time tracking system.",
      trans_li1: "Covering all industrial routes nationwide",
      trans_li2: "Quality and safety control throughout the route",
      trans_li3: "Supports the transportation of sensitive automotive parts",
      trans_li4: "Works in alignment with the warehouse management system",
      trans_sec1_title: "Covering All Industrial Routes Nationwide",
      trans_sec1_desc: "Providing transportation services covering all regions and major industrial estates nationwide, efficiently planning routes to ensure on-time delivery, flexibly supporting both regular and urgent transportation needs.",
      trans_sec2_title: "Quality and Safety Control Throughout the Route",
      trans_sec2_desc: "Operating under safety and quality standards at every step, from receiving goods to storage and final delivery, with continuous tracking and status verification to reduce risks and build maximum confidence.",
      trans_sec3_title: "Supports the Transportation of Sensitive Automotive Parts",
      trans_sec3_desc: "Fully equipped to handle and transport parts requiring special care, using specialized equipment and standardized handling procedures to prevent damage during transit and preserve full product quality until it reaches the destination.",
      
      sup_title: "Supply Management",
      sup_subtitle: "Smart Packaging Management System",
      sup_desc: "Elevating packaging management with a comprehensive Packaging Supply Management System that tracks accurately and reduces hidden costs in the production process.",
      sup_li1: "Returnable Packaging Tracking",
      sup_li2: "Packaging Inventory Management",
      sup_li3: "Data Analytics & Planning",
      sup_li4: "Effectively reducing losses and missing packaging",
      sup_sec1_title: "Packaging Status Tracking",
      sup_sec1_desc: "Systematically tracking the circulation of reusable packaging from dispatch to use and return, reducing losses, increasing transparency, and efficiently controlling costs.",
      sup_sec2_title: "Packaging Inventory Management",
      sup_sec2_desc: "Controlling packaging inventory volume to suit actual workloads, checking real-time stock balances to reduce shortages or unnecessary overstocking.",
      sup_sec3_title: "Data Analytics and Planning",
      sup_sec3_desc: "Using operational data to analyze trends and performance for planning packaging allocations in line with workload volume, increasing decision-making accuracy and reducing long-term costs.",
      
      card_inventory: "Packaging Inventory Management",
      card_dev: "Comprehensive Packaging Design Innovation",
      card_personnel: "Specialized Expert Personnel",
      card_sensitive: "Supports Sensitive Automotive Parts Transport",
      card_route: "Covering All Industrial Routes Nationwide"
    }
  },
  zh: {
    service: {
      dev_title: "包装开发",
      dev_subtitle: "全面的包装设计创新",
      dev_desc: "为汽车行业提供全面的包装开发和设计服务，涵盖纸张、钢铁、木材和塑料等多种材料，专注于适合运输和存储的坚固安全设计。公司的包装开发流程系统化运作，从概念设计、原型制作、实际测试到最终批准，原型开发周期短至7天，以快速准确地响应客户需求。",
      dev_sec1_title: "内部工程",
      dev_sec1_desc: "我们的团队拥有丰富的经验和专业知识，不仅仅生产标准包装，更密切根据每个项目的特定需求定制专属工程解决方案。",
      dev_sec2_title: "数字系统与创新",
      dev_sec2_desc: "由我们自己的内部团队开发运输管理系统 (TMS)，以确保系统无缝对接每位客户的各类规范和需求。",
      dev_sec3_title: "先进工具与技术",
      dev_sec3_desc: "采用AutoCAD和SolidWorks 3D等世界级软件打造高精度复杂包装结构，并在材料准备中应用数字切割优化系统（Digital-Cutting Optimization System）减少浪费并加快生产。",
      
      wh_title: "仓库与运营",
      wh_subtitle: "专业的仓储与运营管理",
      wh_desc: "提供从收货、存储、抽样检查到货物分配的全面仓库管理，达到国际标准，确保您的生产流程不间断。",
      wh_li1: "分类明确易于访问的存储系统 (Smart Storage)",
      wh_li2: "快速、正确、准确的运营 (Fast Operation)",
      wh_li3: "专业专家人员 (Professional Staff)",
      wh_li4: "与您的供应链系统进行数据集成",
      wh_sec1_title: "分类且易于访问的存储系统",
      wh_sec1_desc: "系统化设计的存储空间，根据产品类型和使用频率清晰分类，实现快速检索，减少错误，并最大化仓库空间管理效率。",
      wh_sec2_title: "快速、正确且准确的运营",
      wh_sec2_desc: "在清晰的标准程序下运作，配备支持系统减少冗余和错误，在持续控制质量及按时满足客户需求的同时加快运营。",
      wh_sec3_title: "专业专家人员",
      wh_sec3_desc: "我们的团队由经过培训的专业人员组成，在物流和仓储方面拥有直接经验。他们详细了解运营程序，能专业分析并解决复杂情况，确保运营顺畅高效。",
      
      trans_title: "内部车队运输",
      trans_subtitle: "全面的智能运输系统",
      trans_desc: "利用我们公司配备实时跟踪系统的自营车队（In-house Fleet），提供快速、准时和安全的运输服务。",
      trans_li1: "覆盖全国所有工业路线",
      trans_li2: "全程路线质量与安全控制",
      trans_li3: "支持敏感汽车零部件的运输",
      trans_li4: "与仓库管理系统协同工作",
      trans_sec1_title: "覆盖全国所有工业路线",
      trans_sec1_desc: "提供覆盖全国各地区和主要工业园区的运输服务，高效规划路线以确保准时发货，灵活支持常规和紧急运输需求。",
      trans_sec2_title: "全程质量与安全控制",
      trans_sec2_desc: "在每个环节按照安全和质量标准运作，从收货到存储及最终交付，持续进行跟踪和状态验证，减少风险以建立最高信心。",
      trans_sec3_title: "支持敏感汽车零部件的运输",
      trans_sec3_desc: "全面配备专用设备和标准化处理程序，妥善处理和运输需要特别护理的零部件，防止运输途中损坏，完好保护产品质量直至目的地。",
      
      sup_title: "供应管理",
      sup_subtitle: "智能包装管理系统",
      sup_desc: "通过全面的包装供应管理系统（Packaging Supply Management System）提升包装管理水平，实现精确追踪并降低生产过程中的隐藏成本。",
      sup_li1: "可回收包装追踪 (Returnable Packaging Tracking)",
      sup_li2: "包装库存管理 (Inventory Management)",
      sup_li3: "数据分析与规划 (Data Analytics & Planning)",
      sup_li4: "有效减少包装损耗和丢失",
      sup_sec1_title: "包装状态追踪",
      sup_sec1_desc: "系统性追踪可重复使用包装的出库流转、使用及回收状况，减少丢失，提高透明度，实现成本的有效控制。",
      sup_sec2_title: "包装库存管理",
      sup_sec2_desc: "将包装库存量控制在匹配实际工作量的水平，检查实时库存余量，减少短缺或不必要的过剩库存。",
      sup_sec3_title: "数据分析与规划",
      sup_sec3_desc: "利用运营数据分析趋势与绩效，根据工作量规划包装分配，提高决策的准确性，降低长期成本。",
      
      card_inventory: "包装库存管理",
      card_dev: "全面的包装设计创新",
      card_personnel: "专业专家人员",
      card_sensitive: "支持敏感汽车零部件的运输",
      card_route: "覆盖全国所有工业路线"
    }
  },
  jp: {
    service: {
      dev_title: "パッケージング開発",
      dev_subtitle: "包括的なパッケージ設計革新",
      dev_desc: "紙、鉄、木材、プラスチックなど幅広い素材を網羅し、輸送や保管に適した頑丈で安全な設計に焦点を当てた、自動車業界向けの総合的なパッケージ開発および設計サービスを提供しています。当社のパッケージ開発プロセスは、コンセプト設計、プロトタイピング、実用テストから最終承認まで体系的に運用され、お客様のニーズに迅速かつ正確に対応するための「7日以内のプロトタイピング」枠組みの下で行われます。",
      dev_sec1_title: "社内エンジニアリング",
      dev_sec1_desc: "経験と専門知識に溢れる当社のチームは、単に標準パッケージを生産するだけでなく、各プロジェクトの特定の要件に合わせたエンジニアリングソリューションを密接に設計します。",
      dev_sec2_title: "デジタルシステムと革新",
      dev_sec2_desc: "システムが各顧客の多様な要件やニーズにシームレスに対応できるよう、社内チームで輸送管理システム（TMS System）を開発しています。",
      dev_sec3_title: "高度なツールと技術",
      dev_sec3_desc: "AutoCADやSolidWorks 3Dなどの世界規模のソフトウェアを使用して、高精度かつ複雑なパッケージ構造を作成し、無駄の削減と生産の加速を図るため、材料準備にデジタルカッティング最適化システムを導入しています。",
      
      wh_title: "倉庫と運用",
      wh_subtitle: "プロフェッショナルな倉庫および運用管理",
      wh_desc: "国際基準を採用し、荷受、保管、抜き取り検査、配送まで包括的に倉庫を管理し、お客様の生産プロセスを中断させません。",
      wh_li1: "分類されアクセスしやすい保管システム (Smart Storage)",
      wh_li2: "迅速、正確、的確な運用 (Fast Operation)",
      wh_li3: "専門知識を備えたスタップ (Professional Staff)",
      wh_li4: "サプライチェーンシステムとのデータ統合",
      wh_sec1_title: "カテゴリー別に分類されアクセスしやすい保管システム",
      wh_sec1_desc: "製品の種類と使用頻度によって明確に分類された体系的なストレージスペースにより、迅速なピッキングが可能になり、エラーが減少し、倉庫スペースの管理効率が最大化されます。",
      wh_sec2_title: "迅速、正確、的確な運用",
      wh_sec2_desc: "明確な標準手順の下で運用され、冗長性やエラーを削減するサポートシステムを備えることで、顧客の要求を時間通りに満たしつつ、継続的な品質管理および運用のスピードアップを実現します。",
      wh_sec3_title: "専門知識を備えたスタップ",
      wh_sec3_desc: "当社のチームは、物流や倉庫管理の実務経験を持つ訓練された専門家で構成されています。作業手順を詳細に理解しており、問題を分析し状況を専門的に解決して、スムーズで高効率な運用を実現します。",
      
      trans_title: "自社車両による輸送",
      trans_subtitle: "包括的スマート輸送システム",
      trans_desc: "自社フリート(Inhouse Fleet)とリアルタイム追跡システムを使用した、迅速、オンタイム、そして安全な輸送サービス。",
      trans_li1: "国内すべての産業ルートを網羅",
      trans_li2: "ルート全体の品質および安全管理",
      trans_li3: "繊細な自動車部品の輸送に対応",
      trans_li4: "倉庫管理システムと連携した運用",
      trans_sec1_title: "国内すべての産業ルートを網羅",
      trans_sec1_desc: "全国の全地域および主要工業団地をカバーする輸送サービスを提供し、ルートを効率的に計画して、納期通りの配送を実現。定期配送と緊急配送の両方を柔軟にサポートします。",
      trans_sec2_title: "ルート全体にわたる品質および安全管理",
      trans_sec2_desc: "商品の受け取りから保管、最終配送まで、すべてのステップで安全・品質基準に従って業務を遂行し、リスクを軽減し信頼を構築するために継続的な状況追跡・確認を実施します。",
      trans_sec3_title: "繊細な自動車部品の輸送に対応",
      trans_sec3_desc: "特別な注意を要する部品の取り扱いと輸送に完全対応。専用機器と標準化された取り扱い手順により、輸送中の損傷を防ぎ、目的地まで完全な品質を維持します。",
      
      sup_title: "サプライマネジメント",
      sup_subtitle: "スマートパッケージ管理システム",
      sup_desc: "正確な追跡と生産工程における隠れたコスト削減を実現する、包括的なパッケージング供給管理システム(Packaging Supply Management System)により、パッケージ管理を向上させます。",
      sup_li1: "返却可能なパッケージの追跡 (Returnable Packaging Tracking)",
      sup_li2: "パッケージ在庫管理 (Inventory Management)",
      sup_li3: "データ分析と計画 (Data Analytics & Planning)",
      sup_li4: "パッケージの紛失や損失を効果的に削減",
      sup_sec1_title: "パッケージのステータス追跡",
      sup_sec1_desc: "出荷から使用、返却までの再利用可能パッケージの循環を体系的に追跡し、紛失を減らし、透明性を高め、コストを効果的に管理します。",
      sup_sec2_title: "パッケージ在庫管理",
      sup_sec2_desc: "実際の作業量に合わせて適切なパッケージ在庫量を管理。在庫残高をリアルタイムで確認し、不足や過剰在庫を減らします。",
      sup_sec3_title: "データ分析と計画",
      sup_sec3_desc: "運用データを用いて傾向や実績を分析し、作業量に応じたパッケージの割当を計画。これにより、意思決定の正確性が向上し、長期的なコスト削減につながります。",
      
      card_inventory: "パッケージ在庫管理",
      card_dev: "包括的なパッケージ設計革新",
      card_personnel: "専門知識を備えたスタップ",
      card_sensitive: "繊細な自動車部品の輸送に対応",
      card_route: "国内すべての産業ルートを網羅"
    }
  }
};

const dirs = ['tnb', 'koch'];
for (const dir of dirs) {
  for (const lang of Object.keys(translations)) {
    const filePath = path.join(dir, 'lang', lang + '.json');
    if (fs.existsSync(filePath)) {
      const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
      data.service = translations[lang].service;
      fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
      console.log('Updated ' + filePath);
    }
  }
}
